### PR TITLE
Simplified

### PR DESCRIPTION
**Pull request by Luthor614**
-Fixed my lack of double spaces (for consistency and all)
-Kept terrestrial patch simple

### CODE REVIEW

**Comment by Fevix** [comment]
If you use a program like Notepad++ or Sublime Text, you can set it to put 2 spaces in whenever you hit Tab.

**Comment by Luthor614** [comment]
Oh yah? Never knew, thx for the tip dude :) What I've been doing normally
is just running them through Kawa's json linter but literally forgot to
this time around! I was rushing to get it sent out last night before I
passed out.

**Comment by Fevix** [comment]
Sublime Text does tend to nag you to buy a license, but it's indeed free. Just click "no" on the rare occasions it pops up. (I've had it for ~6 months and have only been prompted 2 or 3 times.)

It'll also automatically fill in closing brackets (Like when you put a "{" in, it'll put a "}" in after it, and place your cursor inbetween. If you put your own "}" after it, it'll remove the automatic "}" it put in. 

You can also tell it "Hey, this file type (.chest, .dungeon, .whateverstarboundfileyouset) is JSON (Which all Starbound mod files are), so give me colors and highlighting relevant to JSON!"

**Comment by Luthor614** [comment]
Really? Huh. Wouldyalookatthat. Thanks Fev, may have to check that out
instead of Notepad++. Wouldn't mind a program that makes me not screw shit
up!!!

-L

**Pull request merged**
