### PR TITLE
FIXED all my armors

### PR DESCRIPTION
**Pull request by Luthor614**
-Stupid copy-paste resulting in triple helmet recipes, argh! All fixed
up and ready to go ;-)
-Also changed a pixel in the village dungeon, added biome background
instead of a glass tile, looks better IMO.
-Armor progresses as normal for recipe unlocking, i.e. craft tier4 and tier5a/m/s recipes unlock via their respective tables, same goes for tier6a/m/6.
-Hopefully that's it and nothing else goes wrong lol

### CODE REVIEW

**Comment by Luthor614** [comment]
Let's try that again ;-)

**Comment by Fevix** [comment]
I noticed you removed all the avali cooking recipes, too, not just the armor/weapon stuff :P

**Comment by Luthor614** [comment]
The projectiles unlock as you craft the pre-required rifles :) and I've just looked over the previous patch and they're weren't any food items....avali cooking station just mimics vanilla so you don't need to edit the config file. I'll do some more testing just to be safe!

**Comment by Luthor614** [comment]
Double checked and foodies are still alright my friend :) no need to add em' to the patch.

**Pull request merged**
